import { TProduct, TReview } from "@/types/types";



export const reviewsData: TReview[] = [
  {
    id: "1",
    name: "Rafiqul Islam",
    email: "rafiq.islam@example.com",
    profileImage: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 5,
    comment:
      "Absolutely love these sunglasses! The build quality feels premium and they look even better in person. Perfect fit and very comfortable for all-day wear.",
    date: "2025-04-06",
    helpful: 24,
    unhelpful: 1,
    verified: true,
    images: ["https://images.pexels.com/photos/2587370/pexels-photo-2587370.jpeg?auto=compress&cs=tinysrgb&w=600", "https://images.pexels.com/photos/2587371/pexels-photo-2587371.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
  {
    id: "2",
    name: "Farhana Akter",
    email: "farhana.akter@example.com",
    profileImage: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 5,
    comment:
      "Stylish and lightweight! I've received so many compliments already. The lenses are clear and provide excellent protection from sunlight.",
    date: "2025-04-05",
    helpful: 18,
    unhelpful: 0,
    verified: true,
    images: ["https://images.pexels.com/photos/2587372/pexels-photo-2587372.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
  {
    id: "3",
    name: "Shahid Hossain",
    email: "shahid.hossain@example.com",
    profileImage: "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 4,
    comment:
      "Great value for the price. The design is modern and elegant. Delivery was fast and packaging was impressive.",
    date: "2025-04-04",
    helpful: 12,
    unhelpful: 1,
    verified: true,
    images: [],
  },
  {
    id: "4",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@example.com",
    profileImage: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 4,
    comment:
      "Very happy with my purchase! The frame feels durable and the lenses reduce glare perfectly. Will definitely order again.",
    date: "2025-04-03",
    helpful: 9,
    unhelpful: 0,
    verified: true,
    images: ["https://images.pexels.com/photos/2587373/pexels-photo-2587373.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
  {
    id: "5",
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@example.com",
    profileImage: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 5,
    comment:
      "Excellent product! The polarized lenses make a huge difference while driving. Highly recommend these to anyone looking for quality eyewear.",
    date: "2025-04-02",
    helpful: 31,
    unhelpful: 2,
    verified: true,
    images: ["https://images.pexels.com/photos/2587374/pexels-photo-2587374.jpeg?auto=compress&cs=tinysrgb&w=600", "https://images.pexels.com/photos/2587375/pexels-photo-2587375.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
  {
    id: "6",
    name: "Tahmina Begum",
    email: "tahmina.begum@example.com",
    profileImage: "https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 5,
    comment:
      "Beautiful design and perfect fit! The UV protection is excellent. My husband loved them so much I had to order another pair for myself.",
    date: "2025-04-01",
    helpful: 15,
    unhelpful: 0,
    verified: true,
    images: ["https://images.pexels.com/photos/2587376/pexels-photo-2587376.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
  {
    id: "7",
    name: "Kamal Hossain",
    email: "kamal.hossain@example.com",
    profileImage: "https://images.pexels.com/photos/1855582/pexels-photo-1855582.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 4,
    comment:
      "Solid build quality and very stylish. The case included is also premium. Slightly tight on the first wear but adjusted nicely.",
    date: "2025-03-30",
    helpful: 8,
    unhelpful: 1,
    verified: true,
    images: [],
  },
  {
    id: "8",
    name: "Shamima Akhtar",
    email: "shamima.akhtar@example.com",
    profileImage: "https://images.pexels.com/photos/1082962/pexels-photo-1082962.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 5,
    comment:
      "Perfect summer accessory! Lightweight and comfortable. The gradient lenses look stunning and provide great visibility.",
    date: "2025-03-28",
    helpful: 22,
    unhelpful: 1,
    verified: true,
    images: ["https://images.pexels.com/photos/2587377/pexels-photo-2587377.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
  {
    id: "9",
    name: "Mahbubur Rahman",
    email: "mahbub.rahman@example.com",
    profileImage: "https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 4,
    comment:
      "Good quality for the price. The frame feels sturdy and the lenses are scratch-resistant. Fast shipping from Bangladesh warehouse.",
    date: "2025-03-25",
    helpful: 14,
    unhelpful: 2,
    verified: true,
    images: ["https://images.pexels.com/photos/2587378/pexels-photo-2587378.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
  {
    id: "10",
    name: "Nasrin Sultana",
    email: "nasrin.sultana@example.com",
    profileImage: "https://images.pexels.com/photos/1885081/pexels-photo-1885081.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
    rating: 5,
    comment:
      "Best sunglasses I've ever owned! The customer service was also very helpful when I had questions about sizing. Will buy again for gifts.",
    date: "2025-03-22",
    helpful: 27,
    unhelpful: 0,
    verified: true,
    images: ["https://images.pexels.com/photos/2587379/pexels-photo-2587379.jpeg?auto=compress&cs=tinysrgb&w=600", "https://images.pexels.com/photos/2587380/pexels-photo-2587380.jpeg?auto=compress&cs=tinysrgb&w=600"],
  },
];


export const productMockData: TProduct = {
    id: "1",
    img: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
    title: "Black Horizon Sunglasses",
    color: "#232323",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "20",
    priceAfterDiscount: 1200,
    mainPrice: 1500,
    shortDescription: "A luxury purple frame that exudes sophistication and class.",
    longDescription: "Purple Horizon sunglasses are the epitome of luxury. With their rich purple color and elegant design, they are perfect for those who want to add a touch of class to their accessory collection.",
    brand: "Elite Styles",
    material: "Metal Alloy",
    dimensions: "Medium",
    weight: "170g",
    shippingInfo: "Currently out of stock",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Anti-Scratch",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "France",
    targetAudience: "Unisex, Luxury Seekers",
    careInstructions: "Store in a protective case. Clean lenses with a microfiber cloth.",
    averageRating: 4.5,
    totalReviews: 100,
    isFeatured: true,
    variants: [
      {
        id: "11",
        title: "Black Horizon",
        color: "#232323",
        priceAfterDiscount: 1200,
        mainPrice: 1500,
        discountPercent: 20,
        inStock: true,
        quantity: 5,
        productCode: "BL-2025-001",
        shortDescription: "A luxury black frame that exudes sophistication and class.",
        imgList: [
          {
            image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "111",
          },
          {
            image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "112",
          },
        ],
      },
      {
        id: "12",
        title: "Blue Horizon",
        color: "#1d81c8",
        priceAfterDiscount: 120,
        mainPrice: 150,
        discountPercent: 20,
        inStock: false,
        quantity: 0,
        productCode: "NA1-2025-002",
        shortDescription: "A luxury blue frame that exudes sophistication and class.",
        imgList: [
          {
            image: "https://i.ibb.co.com/qMPcw4zJ/Chat-GPT-Image-Apr-4-2025-03-27-28-PM.png",
            id: "321",
          },
        ],
      },
    ],
  }



export const mockProducts: TProduct[] = [
  {
    id: "1",
    img: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
    title: "Black Horizon Sunglasses",
    color: "#232323",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "20",
    priceAfterDiscount: 1200,
    mainPrice: 1500,
    shortDescription: "A luxury purple frame that exudes sophistication and class.",
    longDescription: "Purple Horizon sunglasses are the epitome of luxury. With their rich purple color and elegant design, they are perfect for those who want to add a touch of class to their accessory collection.",
    brand: "Elite Styles",
    material: "Metal Alloy",
    dimensions: "Medium",
    weight: "170g",
    shippingInfo: "Currently out of stock",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Anti-Scratch",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "France",
    targetAudience: "Unisex, Luxury Seekers",
    careInstructions: "Store in a protective case. Clean lenses with a microfiber cloth.",
    averageRating: 4.5,
    totalReviews: 100,
    isFeatured: true,
    category: "all",
    variants: [
      {
        id: "11",
        title: "Black Horizon",
        color: "#232323",
        priceAfterDiscount: 1200,
        mainPrice: 1500,
        discountPercent: 20,
        inStock: true,
        quantity: 5,
        productCode: "BL-2025-001",
        shortDescription: "A luxury black frame that exudes sophistication and class.",
        imgList: [
          {
            image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "111",
          },
          {
           image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "112",
          },
        ],
      },
       {
        id: "12",
        title: "Blue Horizon",
        color: "#1d81c8",
        priceAfterDiscount: 120,
        mainPrice: 150,
        discountPercent: 20,
        inStock: true,
        quantity: 10,
        productCode: "NA1-2025-002",
        shortDescription: "A luxury blue frame that exudes sophistication and class.",
        imgList: [
          {
            image: "https://i.ibb.co.com/qMPcw4zJ/Chat-GPT-Image-Apr-4-2025-03-27-28-PM.png",
            id: "321",
          },
        ],
      },
       {
        id: "13",
        title: "Black Horizon 2",
        color: "#232323",
        priceAfterDiscount: 1200,
        mainPrice: 1500,
        discountPercent: 20,
        inStock: true,
        quantity: 5,
        productCode: "BL-2025-001",
        shortDescription: "A luxury black frame that exudes sophistication and class.",
        imgList: [
          {
            image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "111",
          },
          {
           image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "112",
          },
        ],
      },
    ],
  },
  {
    id: "2",
    img: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
    title: "Silver Horizon Sunglasses",
    color: "#c0c0c0",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "18",
    priceAfterDiscount: 1300,
    mainPrice: 1600,
    shortDescription: "A sleek and modern silver frame for a minimalist style.",
    longDescription: "Silver Horizon sunglasses are perfect for those who prefer a clean and sharp look. Their lightweight design makes them an excellent choice for everyday wear.",
    brand: "Elite Styles",
    material: "Metal Alloy",
    dimensions: "Medium",
    weight: "180g",
    shippingInfo: "Available for immediate shipment",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Polarized",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "Italy",
    targetAudience: "Unisex, Minimalist Seekers",
    careInstructions: "Store in a protective case. Wipe lenses with a microfiber cloth.",
    averageRating: 4.2,
    totalReviews: 120,
    isFeatured: false,
     category: "aviator",
    variants: [
      {
        id: "21",
        title: "Silver Horizon",
        color: "#c0c0c0",
        priceAfterDiscount: 1300,
        mainPrice: 1600,
        discountPercent: 18,
        inStock: true,
        quantity: 10,
        productCode: "SV-2025-001",
        shortDescription: "A luxury silver frame that exudes sophistication and class.",
        imgList: [
          {
            image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "111",
          },
          {
           image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "112",
          },
        ],
      },
    ],
  },
  {
    id: "3",
    img: "https://i.ibb.co.com/red-image1.png",
    title: "Red Horizon Sunglasses",
    color: "#e0241b",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "20",
    priceAfterDiscount: 1100,
    mainPrice: 1400,
    shortDescription: "A bold red frame that makes a statement in style.",
    longDescription: "Red Horizon sunglasses are designed for those who are bold and unapologetic. Their striking red color ensures that you stand out in any crowd.",
    brand: "Elite Styles",
    material: "Plastic",
    dimensions: "Medium",
    weight: "160g",
    shippingInfo: "Currently out of stock",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Anti-Scratch",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "USA",
    targetAudience: "Unisex, Bold Fashion Enthusiasts",
    careInstructions: "Store in a case. Clean lenses with a microfiber cloth.",
    averageRating: 4.8,
    totalReviews: 80,
    isFeatured: true,
     category: "wayfarer",
    variants: [
      {
        id: "31",
        title: "Red Horizon",
        color: "#e0241b",
        priceAfterDiscount: 1100,
        mainPrice: 1400,
        discountPercent: 20,
        inStock: true,
        quantity: 6,
        productCode: "RD-2025-001",
        shortDescription: "A bold red frame for those who love to make a statement.",
        imgList: [
          {
           image: "https://i.ibb.co.com/qMPcw4zJ/Chat-GPT-Image-Apr-4-2025-03-27-28-PM.png",
            id: "311",
          },
        ],
      },  {
        id: "11",
        title: "Black Horizon",
        color: "#232323",
        priceAfterDiscount: 1200,
        mainPrice: 1500,
        discountPercent: 20,
        inStock: false,
        quantity: 0,
        productCode: "BL-2025-001",
        shortDescription: "A luxury black frame that exudes sophistication and class.",
        imgList: [
          {
            image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "111",
          },
          {
           image: "https://i.ibb.co.com/jkktXJFP/Chat-GPT-Image-Apr-4-2025-03-18-44-PM.png",
            id: "112",
          },
        ],
      },
    ],
  },
  {
    id: "4",
    img: "https://i.ibb.co.com/silver-edition.png",
    title: "Silver Edition Sunglasses",
    color: "#b0b0b0",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "16",
    priceAfterDiscount: 1350,
    mainPrice: 1600,
    shortDescription: "A stylish silver frame for a bold, modern look.",
    longDescription: "Silver Edition sunglasses bring a cutting-edge design that is perfect for those who want to add some flair to their fashion collection. With UV protection and a contemporary frame, these sunglasses are both trendy and functional.",
    brand: "Shiny Styles",
    material: "Aluminum Alloy",
    dimensions: "Medium",
    weight: "165g",
    shippingInfo: "Available for immediate shipment",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Anti-Glare",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "Germany",
    targetAudience: "Unisex, Trendy Seekers",
    careInstructions: "Store in a protective case. Wipe lenses with a microfiber cloth.",
    averageRating: 4.5,
    totalReviews: 90,
    isFeatured: false,
     category: "luxury",
    variants: [
      {
        id: "41",
        title: "Silver Edition",
        color: "#b0b0b0",
        priceAfterDiscount: 1350,
        mainPrice: 1600,
        discountPercent: 16,
        inStock: true,
        quantity: 12,
        productCode: "SE-2025-001",
        shortDescription: "A stylish silver frame for a bold, modern look.",
        imgList: [
          {
            image: "https://i.ibb.co.com/silver-edition.png",
            id: "411",
          },
        ],
      },
    ],
  },
  {
    id: "5",
    img: "https://i.ibb.co.com/gold-horizon.png",
    title: "Gold Horizon Sunglasses",
    color: "#d4af37",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "22",
    priceAfterDiscount: 1400,
    mainPrice: 1800,
    shortDescription: "A stunning gold frame for a luxurious touch to your wardrobe.",
    longDescription: "Gold Horizon sunglasses offer a classic design with a luxurious golden frame, perfect for anyone who loves the finer things in life. With their sophisticated style, these sunglasses provide both elegance and UV protection.",
    brand: "Golden Vision",
    material: "Metal Alloy",
    dimensions: "Large",
    weight: "180g",
    shippingInfo: "Available for immediate shipment",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Polarized",
    warranty: "2-year warranty for manufacturing defects",
    countryOfOrigin: "Switzerland",
    targetAudience: "Unisex, Luxury Seekers",
    careInstructions: "Store in a case. Clean lenses with a microfiber cloth.",
    averageRating: 4.7,
    totalReviews: 110,
    isFeatured: true,
     category: "all",
    variants: [
      {
        id: "51",
        title: "Gold Horizon",
        color: "#d4af37",
        priceAfterDiscount: 1400,
        mainPrice: 1800,
        discountPercent: 22,
        inStock: true,
        quantity: 8,
        productCode: "GH-2025-001",
        shortDescription: "A stunning gold frame that exudes luxury.",
        imgList: [
          {
            image: "https://i.ibb.co.com/gold-horizon.png",
            id: "511",
          },
        ],
      },
    ],
  },
  {
    id: "6",
    img: "https://i.ibb.co.com/black-knight.png",
    title: "Black Knight Sunglasses",
    color: "#000000",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "21",
    priceAfterDiscount: 950,
    mainPrice: 1200,
    shortDescription: "A sleek black frame with subtle detailing for a modern style.",
    longDescription: "Black Knight sunglasses are designed for those who appreciate minimalist, modern designs with the perfect amount of flair. The UV protection ensures your eyes are safe while maintaining a sleek, stylish appearance.",
    brand: "Black Knight",
    material: "Plastic",
    dimensions: "Medium",
    weight: "150g",
    shippingInfo: "Available for immediate shipment",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Anti-Reflective",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "USA",
    targetAudience: "Unisex, Minimalist Seekers",
    careInstructions: "Store in a case. Wipe lenses with a microfiber cloth.",
    averageRating: 4.6,
    totalReviews: 95,
    isFeatured: false,
     category: "all",
    variants: [
      {
        id: "61",
        title: "Black Knight",
        color: "#000000",
        priceAfterDiscount: 950,
        mainPrice: 1200,
        discountPercent: 21,
        inStock: true,
        quantity: 10,
        productCode: "BK-2025-001",
        shortDescription: "A sleek black frame for a modern style.",
        imgList: [
          {
            image: "https://i.ibb.co.com/black-knight.png",
            id: "611",
          },
        ],
      },
    ],
  },
  {
    id: "7",
    img: "https://i.ibb.co.com/clear-vision.png",
    title: "Clear Vision Sunglasses",
    color: "#f4f4f4",
    inStock: false,
    reviews: reviewsData,
    discountPercent: "21",
    priceAfterDiscount: 1100,
    mainPrice: 1400,
    shortDescription: "A stylish transparent frame that matches any outfit.",
    longDescription: "Clear Vision sunglasses offer a unique transparent frame that’s perfect for those who want to make a subtle yet fashionable statement. The UV400 lenses provide full protection while maintaining a light and airy aesthetic.",
    brand: "Clear Vision",
    material: "Plastic",
    dimensions: "Small",
    weight: "140g",
    shippingInfo: "Currently out of stock",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Anti-Scratch",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "France",
    targetAudience: "Unisex, Fashion Seekers",
    careInstructions: "Store in a case. Clean lenses with a microfiber cloth.",
    averageRating: 4.4,
    totalReviews: 85,
    isFeatured: false,
     category: "all",
    variants: [
      {
        id: "71",
        title: "Clear Vision",
        color: "#f4f4f4",
        priceAfterDiscount: 1100,
        mainPrice: 1400,
        discountPercent: 21,
        inStock: false,
        quantity: 0,
        productCode: "CV-2025-001",
        shortDescription: "A stylish transparent frame that matches any outfit.",
        imgList: [
          {
            image: "https://i.ibb.co.com/clear-vision.png",
            id: "711",
          },
        ],
      },
    ],
  },
  {
    id: "8",
    img: "https://i.ibb.co.com/silver-mirage.png",
    title: "Silver Mirage Sunglasses",
    color: "#c0c0c0",
    inStock: true,
    reviews: reviewsData,
    discountPercent: "18",
    priceAfterDiscount: 1300,
    mainPrice: 1600,
    shortDescription: "A sleek silver frame that gives off a futuristic vibe.",
    longDescription: "Silver Mirage sunglasses feature a sharp silver frame with reflective lenses for a bold, futuristic look. These sunglasses are perfect for those who want to stand out with modern elegance.",
    brand: "Silver Mirage",
    material: "Aluminum Alloy",
    dimensions: "Medium",
    weight: "170g",
    shippingInfo: "Available for immediate shipment",
    frameType: "Full-Rim",
    lensType: "UV400 Protection, Polarized",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "Germany",
    targetAudience: "Unisex, Futuristic Seekers",
    careInstructions: "Store in a case. Wipe lenses with a microfiber cloth.",
    averageRating: 4.3,
    totalReviews: 70,
    isFeatured: false,
     category: "all",
    variants: [
      {
        id: "81",
        title: "Silver Mirage",
        color: "#c0c0c0",
        priceAfterDiscount: 1300,
        mainPrice: 1600,
        discountPercent: 18,
        inStock: true,
        quantity: 5,
        productCode: "SM-2025-001",
        shortDescription: "A sleek silver frame for a futuristic look.",
        imgList: [
          {
            image: "https://i.ibb.co.com/silver-mirage.png",
            id: "811",
          },
        ],
      },
    ],
  },
  {
    id: "9",
    img: "https://i.ibb.co.com/black-ace.png",
    title: "Black Ace Sunglasses",
    color: "#000000",
    inStock: false,
    reviews: reviewsData,
    discountPercent: "23",
    priceAfterDiscount: 1150,
    mainPrice: 1500,
    shortDescription: "A bold and stylish pair of black frame sunglasses with a unique design.",
    longDescription: "These Black Ace sunglasses feature a bold black frame and polarized lenses, offering maximum protection and style. Their distinctive design ensures you’ll stand out from the crowd.",
    brand: "Black Ace",
    material: "Polycarbonate",
    dimensions: "Medium",
    weight: "180g",
    shippingInfo: "Currently out of stock",
    frameType: "Full-Rim",
    lensType: "Polarized, UV400 Protection",
    warranty: "1-year warranty for manufacturing defects",
    countryOfOrigin: "Japan",
    targetAudience: "Unisex, Bold Seekers",
    careInstructions: "Store in a protective case. Clean lenses with a microfiber cloth.",
    averageRating: 4.9,
    totalReviews: 60,
    isFeatured: true,
     category: "all",
    variants: [
      {
        id: "91",
        title: "Black Ace",
        color: "#000000",
        priceAfterDiscount: 1150,
        mainPrice: 1500,
        discountPercent: 23,
        inStock: false,
        quantity: 0,
        productCode: "BA-2025-001",
        shortDescription: "A bold pair of sunglasses with a unique black design.",
        imgList: [
          {
            image: "https://i.ibb.co.com/black-ace.png",
            id: "911",
          },
        ],
      },
    ],
  },
];

// Mutate mockProducts in-place at evaluated runtime client-side
if (typeof window !== "undefined") {
  const stored = localStorage.getItem("glassophite_products");
  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      mockProducts.length = 0;
      mockProducts.push(...parsed);
    } catch (e) {
      console.error("Error loading products from localStorage", e);
    }
  } else {
    localStorage.setItem("glassophite_products", JSON.stringify(mockProducts));
  }
}

export const saveProductsToStorage = (products: TProduct[]) => {
  if (typeof window !== "undefined") {
    localStorage.setItem("glassophite_products", JSON.stringify(products));
    // Also keep active reference in-place synced for live UI transitions
    mockProducts.length = 0;
    mockProducts.push(...products);
  }
};
